### ISSUE TITLE
Crash after first cutscene before title screen appeared in Fire Emblem Fates : Special Edition

### ISSUE THREAD

**Issue by kuroneko1235** [valentinvanelslande/citra#16]
After first cutscene finished or skipped, the app crash,  pop up appeared(citra.exe has stopped working)
like in the picture,
![image](https://user-images.githubusercontent.com/45751227/49716184-8bbbf100-fc85-11e8-819f-8de55cd16539.png)

using release version 20181209190228-d34dfed
any solution please? thanks.

**Comment by valentinvanelslande** [comment]
log?

**Comment by kuroneko1235** [comment]
Here 
[log.txt](https://github.com/valentinvanelslande/citra/files/2664527/log.txt)

**Comment by valentinvanelslande** [comment]
@kuroneko1235 we can't help you because you downloaded the game.
