### ISSUE TITLE
Luigi mansion issue resubmit with broken graphics

### ISSUE THREAD

**Issue by Jetleex1** [valentinvanelslande/citra#19]
here is the issue with screenshot

![github](https://user-images.githubusercontent.com/45804321/49861807-8e9e1980-fe1e-11e8-83bd-2bd3307fa215.jpg)

**Comment by valentinvanelslande** [comment]
did you disable shadows?

**Comment by Jetleex1** [comment]
i was running it on stock settings changing graphics option has no effect

**Comment by valentinvanelslande** [comment]
log?

**Comment by Jetleex1** [comment]
[1.txt](https://github.com/valentinvanelslande/citra/files/2672090/1.txt)
