### ISSUE TITLE
Freezes upon asking for name enter

### ISSUE THREAD

**Issue by tsbuilderboy** [valentinvanelslande/citra#268]
Essentially it just hangs and crashes as soon as the keyboard comes on. I have only tested this on Tomodachi Life.

**Comment by valentinvanelslande** [comment]
use cmd to input text...
citra crashes with a lot of symbols (example: ¡)

**Comment by tsbuilderboy** [comment]
Oops, I forgot to delete that. Yeah, I figured out how to use the software keyboard.
