### ISSUE TITLE
Pokemon UltraSun xp problem

### ISSUE THREAD

**Issue by JesusMtz89** [valentinvanelslande/citra#290]
I just started playing pokemon ultrasun and when I beat another pokemon I only get 1xp

**Comment by valentinvanelslande** [comment]
that's impossible
it does not happen in ultra moon
![](https://user-images.githubusercontent.com/22228082/34854044-e18af57a-f6fc-11e7-8bcf-2b5bb030e3f4.PNG)

**Comment by JesusMtz89** [comment]
![img1](https://user-images.githubusercontent.com/30416423/34854999-f1689c8a-f702-11e7-9b20-3cbc9da68148.jpg)

**Comment by valentinvanelslande** [comment]
exp cheat enabled?

**Comment by JesusMtz89** [comment]
No, only the 100% catch cheat, i do not want to use a xp cheat.
Is there a more updated version of the emulator?

**Comment by JesusMtz89** [comment]
Done, I just had to turn off the 100% catch cheat, that was the problem.

**Comment by valentinvanelslande** [comment]
https://github.com/valentinvanelslande/citra/releases/download/106/citra-windows-mingw-20180108-5486022.zip
