### ISSUE TITLE
The Legend of Zelda: Ocarina of Time 3D - Only sound

### ISSUE THREAD

**Issue by Aconcerned** [valentinvanelslande/citra#316]
I checked out the dump, and the dump is fine because it runs on the official Citra, but your emulator can't render the game correctly.

It only displays a black screen, the loading screen and the music.

This only happens in Ocarina of Time, all the others games run fine.

**Comment by valentinvanelslande** [comment]
log?

**Comment by valentinvanelslande** [comment]
![no black screen](https://user-images.githubusercontent.com/22228082/35769698-5cec34e8-08d4-11e8-9789-69b080d01445.PNG)
update the GPU drivers

**Comment by Aconcerned** [comment]
Here is the log if you ask.
https://pastebin.com/piUsNq5t

**Comment by valentinvanelslande** [comment]
update the drivers
