### ISSUE TITLE
Monster Hunter 4 Ultimate

### ISSUE THREAD

**Issue by Bojack87** [valentinvanelslande/citra#324]
Greetings.

MH4U has a few issues.

1)Shadows are not present.

2)Base Performance is poor, requires high Jit tick value, resulting in stuttery gameplay. (anything above 3500 ticks). Game runs at 50%(town)-80%(quest zones) speed at 0-3000 tick rate. 

3)FMV's dont run at all (emulation stops) unless a high tick rate is input (1000+)and run poorly even at insanely high tick rates (20,000)

4)Verticies Per thread limited to 100 max. Changing from 10 to 100 improved emulation speed by 10% ,still have CPU headroom on every thread, could go higher if possible.

Observations using 3930k @4.6ghz CPU + 780ti GPU

Keep up to good work!, it is appreciated :)

**Comment by valentinvanelslande** [comment]
there are no shadows in MH4U in any citra.
see [CPU JIT AddTicks Ticks](https://github.com/valentinvanelslande/citra/wiki/CPU-JIT-AddTicks-Ticks), the games have different fps and bugs according to the ticks.
you can put all the vertices by thread that you want in the ini.

if you put 0 ticks in pokémon x, the game will freeze after selecting the language.
