### ISSUE TITLE
output buffer size not match

### ISSUE THREAD

**Issue by mathieu7107** [valentinvanelslande/citra#334]
I cant start pokemon moon
![citra bug](https://user-images.githubusercontent.com/37053075/36952435-0eaa6306-1fde-11e8-9a04-8d8fb7074d35.png)

**Comment by valentinvanelslande** [comment]
5fc0838953d72ea425ac17af6bf3f54a082f6a67 fixes this?

**Comment by mathieu7107** [comment]
i dont understand. how i doing? thanks for your help

**Comment by valentinvanelslande** [comment]
@mathieu7107 run the updater

**Comment by mathieu7107** [comment]
how i run the updater?
