### ISSUE TITLE
Can't map generic usb controllers on latest builds

### ISSUE THREAD

**Issue by natuschaos** [valentinvanelslande/citra#339]
Hello.

On latest builds I can't  map the gamepad, the emu crash when I try to assign any button, and if I use a config.ini already mapped by others builds like the oficial the emu crash on opening any game.

**Comment by valentinvanelslande** [comment]
move to official repo

**Comment by valentinvanelslande** [comment]
happens in nightly?

**Comment by valentinvanelslande** [comment]
@natuschaos

**Comment by valentinvanelslande** [comment]
@natuschaos log?

**Comment by natuschaos** [comment]
It won't happen on latest nightly-585 o Windows 7.

I changed from Windows 10 to Windows 7 and figured out that the crash is gone in your builds, the culprit must be Windows 10 + Generic controller driver.

Sorry for making this issue, you can close it now at least no one seems to having this issue. I'll stick with Windows 7 as default OS, thanks for making such a nice Citra.

**Comment by valentinvanelslande** [comment]
The citra log is useless, provide a backtrace

**Comment by natuschaos** [comment]
Sorry for not providing any information, I've been busy. About this problem a guy that talks about emulation on YouTube said that the database of joystiscks Citra uses supports a small number of controllers, in the Sick custom build the controller work fine so I think that it can be fixed, not only for me but in the oficial repo of Citra. I'll try to send logs and that backtrace today.
