### ISSUE TITLE
MH4U much worse performance since release 204

### ISSUE THREAD

**Issue by Schokoladenonkel** [valentinvanelslande/citra#347]
Hey, not sure if this is fitting for an issue, but thought I'd report it nonetheless. Since release 204 the performance (fps) in MH4U is notably worse.  In 203 it runs at 100% speed for me for most(all) of the maps in 204 it dips to under 90% alot. Adjusting resolution doesn't improve framerate.

Running on:  GTX 970 /  I5 2500k 3,3 Ghz /  8 Gig of Ram

If you need more info or logs, I'll provide what I can. If this is a non issue or known to you, you can just close this.

Thanks for the work and have a nice day!

**Comment by valentinvanelslande** [comment]
this is probably due to PR 3497
