### ISSUE TITLE
Problems with the Game The Legend Of Zelda Ocarina of Time 3D

### ISSUE THREAD

**Issue by Ceka1** [valentinvanelslande/citra#355]
Im sorry i have a problem with Citra on game The Legend Of Zelda Ocarina of Time 3D that i don't see my items gear and other stuff can u please tell me what to do?

Thank You!

**Comment by valentinvanelslande** [comment]
enable accurate hardware shader

**Comment by Ceka1** [comment]
It crashes when i enable it


2018-04-27 20:28 GMT+02:00 Valentin Vanelslande <notifications@github.com>:
