### ISSUE TITLE
Pokémon Omega Ruby looks worse than before with an Intel HD Graphics

### ISSUE THREAD

**Issue by LOuroboros** [valentinvanelslande/citra#358]
I just tried your latest compiled build _(bbc144d)_ and Pokémon Omega Ruby has a lot of visual glitches that it didn't have before, plus it seems to be freezing on the pokémon summary screen.
So far I've been using one of the builds that you apparently removed for some reason _(d6e011a)_, and that one works perfectly fine.

Here's some pictures comparing the 2 versions.
Left = bbc144d | Right = d6e011a
https://i.imgur.com/0hG14BN.png
https://i.imgur.com/duzJUCw.png
https://i.imgur.com/gngI8v5.png
_GitHub didn't let me upload them directly, so I uploaded them to Imgur instead._

I also made a log, I don't know if it'll be useful though.
https://pastebin.com/un0776fX

**CPU & GPU**: Intel Celeron N2840 and its iGPU, Intel HD Graphics
**OS**: Windows 8.1 x64
**RAM**: 2 GB

**EDIT**: Of course, the game looks and runs okay if I disable "Enable Hardware Shader" which would be the same as using Shader Emulation CPU in older versions, but the performance is naturally worse.

**Comment by valentinvanelslande** [comment]
this happens on Canary?

**Comment by LOuroboros** [comment]
Nope, it doesn't.
https://i.imgur.com/sOQFMWc.png

**Comment by valentinvanelslande** [comment]
test each build and tell me if it has the issue
https://ci.appveyor.com/api/buildjobs/xfjb03yt4myfbima/artifacts/citra-windows-mingw-20180518-a41fa15.7z
https://ci.appveyor.com/api/buildjobs/ny17q7mqu7ld1hmm/artifacts/citra-windows-mingw-20180518-3e839be.7z
https://ci.appveyor.com/api/buildjobs/dvk6sxt1kxm5idrm/artifacts/citra-windows-mingw-20180518-8d83521.7z

**Comment by LOuroboros** [comment]
Build #1 _(a41fa15)_ is bugged too.
Build #2 _(3e839be)_ works perfectly _(although it runs slightly slower than d6e011a)_.
Build #3 _(8d83521)_ works perfectly and it also runs pretty much like d6e011a.

**Comment by valentinvanelslande** [comment]
Report in #3738
