### ISSUE TITLE
OpenGL_Shader error

### ISSUE THREAD

**Issue by Z3roInfinity** [valentinvanelslande/citra#359]
Hi, I have problem running Tomodachi Life. I've been able to run it before I reinstalled my Windows. I've ensured that all of my graphics drivers are up-to-date but I still get this error. Please help. Thank you. 

[citra_log.txt](https://github.com/valentinvanelslande/citra/files/2026294/citra_log.txt)

**Comment by valentinvanelslande** [comment]
Bad drivers, and you're not using my latest build.

**Comment by Z3roInfinity** [comment]
I didn't notice there is a new build. I disabled the Hardware shader option and it worked.
