### ISSUE TITLE
Monster Hunter 4g- frame drop while cutscene and worse performance afterward

### ISSUE THREAD

**Issue by maskedgamer** [valentinvanelslande/citra#360]
edit: using deleted build

**Comment by valentinvanelslande** [comment]
closing because you're using a build that deleted

**Comment by maskedgamer** [comment]
Well, I can see that I must have done something improper. Whatever it is, I'm sorry for it.  Thank you nonetheless.

**Comment by maskedgamer** [comment]
Well, I can see that I must have done something improper. Whatever it is, I'm sorry for it.  Thank you anyway.
