### ISSUE TITLE
Citra #2197d2b316 error to read Peanuts Movie, The - Snoopys Grand Adventure (USA) 

### ISSUE THREAD

**Issue by NekokoTime** [valentinvanelslande/citra#361]
![anotacao 2](https://user-images.githubusercontent.com/38867013/40624381-ab07cacc-6282-11e8-8d70-2855eb901a31.png)

**Comment by valentinvanelslande** [comment]
no log and not tested with nightly

**Comment by valentinvanelslande** [comment]
If you want for me to fix it, add the game to the title keys site

**Comment by valentinvanelslande** [comment]
@NekokoTime no log
