### ISSUE TITLE
Terraria - The game freezes after having to use the Software Keyboard for various things

### ISSUE THREAD

**Issue by LOuroboros** [valentinvanelslande/citra#363]
The title is self-explanatory.
I have Software Keyboard Implemention set to Qt _(StdIn doesn't work. It just freezes the game whenever I have to write the name of my character or my world.)_ and the game always freezes after writing the name of my character or my world.

Here's some examples:
Freeze after setting my character's name: https://streamable.com/fhgwj
Freeze after writing my world's name: https://streamable.com/3tass

Game: Terraria v1.0.1 (USA)
Citra Version: Citra #232 (b32d8d5)

**Comment by valentinvanelslande** [comment]
no log, also happens with nightly?
