### ISSUE TITLE
Cheat issues.

### ISSUE THREAD

**Issue by Rhess86** [valentinvanelslande/citra#367]
Hi, I'm sorry if i shouldn't be doing this here but i thought i could help somehow.
I've downloaded an older version of your emulator that have the cheats working with bravely default and bravely second. The version is HEAD-21744b0. Uppon seeing how the cheats worked i came here and downloaded the most recent version, which runs a lot better but the cheats for these 2 games aren't working. The same cheats with the same game file work on the old version but not on the new of your emulator. I'm not sure if it was edited by the person who posted on a forum that i frequent but i thought maybe you wanted to know. If you want i can post the zip with the old version in case you want to check it out. Thanks for the good work.

**Comment by valentinvanelslande** [comment]
add the cheats in the most recent version
