### ISSUE TITLE
Eula agreement prevents playing Ace Attorney 6 DLC

### ISSUE THREAD

**Issue by Colmines92** [valentinvanelslande/citra#381]
When I try to play Ace Attorney 6 DLC there appears a message like this:

ErrEula
Error Code: 0x00016F78

...without asking anything and the DLC episodes simply doesn't load.

[backlog.txt](https://github.com/valentinvanelslande/citra/files/2215024/backlog.txt)

**Comment by valentinvanelslande** [comment]
Dump the config savegame of your 3DS

**Comment by valentinvanelslande** [comment]
ErrEula is also for showing errors.
what happens with nightly and canary?
logs?

**Comment by valentinvanelslande** [comment]
you are not using the latest build
