### ISSUE TITLE
Shared Font: loading opensource one even having the original

### ISSUE THREAD

**Issue by Colmines92** [valentinvanelslande/citra#383]
From a time ago citra is using the newly included open source font even when I have the dumped "shared_font.bin" placed under <citra_path>"\user\sysdata\"

I suppose it started happening after build 259: Use open source Shared Font if no dumped file is available

I had at hand builds 244 and 285. There are two screenshots showing how it displays in build 244 and 285 using the same user folder:

![244](https://user-images.githubusercontent.com/25232329/43092360-fcdc8bac-8e7a-11e8-98fb-01ba4c3e535f.png)

![285](https://user-images.githubusercontent.com/25232329/43092398-1590ddc4-8e7b-11e8-86a0-4a5739d88af9.png)

I have attached the full logs, but you can see here:

build 244:
[   3.907711] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetSharedFont:200: Loaded shared font by legacy method

build 285:
[   3.330448] Service.FS <Warning> core/file_sys/archive_ncch.cpp:OpenFile:123: Shared Font file missing. Loading open source replacement from memory

[citra_log_244.txt](https://github.com/valentinvanelslande/citra/files/2220376/citra_log_244.txt)
[citra_log_285.txt](https://github.com/valentinvanelslande/citra/files/2220377/citra_log_285.txt)

**Comment by valentinvanelslande** [comment]
issue with pr
