### ISSUE TITLE
Yo-Kai Watch 2 - Psychic Specter (Multiple Issues)

### ISSUE THREAD

**Issue by Omnija** [valentinvanelslande/citra#384]
I've been currently playing Yo-Kai Watch 2  and came across a few issue while playing.

- While playing for about an hour or so, heavy lag and low fps permanently stays. So every 40 mins or so, it's needed to reset to regain full fps.

- Not sure if this game has ever been able to connect locally, but when testing out local connections. I've been able to see host or searcher, but have not been able to establish a connection. Tested (Battle, Medal Swap and Blaster)

**Comment by valentinvanelslande** [comment]
i think that issues happen with official builds, i can't test because my pc does not work
