### ISSUE TITLE
Suggestion for compatibility with MH4U

### ISSUE THREAD

**Issue by Jvtrovao** [valentinvanelslande/citra#400]
MH4U hasn't been playable on the latest versions of citra, but this version of citra (https://drive.google.com/file/d/13S5G5ASjmgbb7NIHOps2ZmGmk-xGTk8K/view) has 3 settings on the Tweaks tab that could help make 4U be playable at 60Fps and have the shadows that your current version of citra has. Its just an ideia to help make one of 3DS best games fully playable.

**Comment by valentinvanelslande** [comment]
i will only add these settings if you give me the source code of that build.
