### ISSUE TITLE
Pokémon Omega Ruby broken in Intel HD Graphics, again.

### ISSUE THREAD

**Issue by LOuroboros** [valentinvanelslande/citra#410]
I noticed that I haven't updated the Citra builds that I regularly use in a while, so I decided to do it today.
I downloaded your latest build (98d8081) and I noticed that Pokémon Omega Ruby was broken, it looked just like it did in #358. Having noticed that, I decided to slowly try older builds in the /releases page until I was able to find the culprit.

The game works correctly with your Citra 350 build (3f2991e), but **it starts to look broken in the Citra 358 build (fe4505a)**.

I guess it's pointless to show this again, but here's some comparison pics.
Up: Citra 350 | Down: Citra 358
![350](https://user-images.githubusercontent.com/4485172/43997447-61abf7e4-9db1-11e8-9db9-e36aed8866e6.png)
![358](https://user-images.githubusercontent.com/4485172/43997448-653b10ac-9db1-11e8-8e74-993ffac6105f.png)

Log:
https://pastebin.com/4A58XWxZ

**CPU & GPU**: Intel Celeron N2840 and its iGPU, Intel HD Graphics
**OS**: Windows 8.1 x64
**RAM**: 2 GB

**Comment by valentinvanelslande** [comment]
Does this happen with the latest canary?
