### ISSUE TITLE
Tomodachi Life Fatal Error

### ISSUE THREAD

**Issue by Gabrielmines** [valentinvanelslande/citra#411]
Tomodachi Life was working before in the old version of citra now the new version is just crashing please fix i want to play this game :(

**Comment by valentinvanelslande** [comment]
no log/screenshot/version

**Comment by Gabrielmines** [comment]
Fuck this im sad now i had a huge family

**Comment by valentinvanelslande** [comment]
It works...
![work](https://user-images.githubusercontent.com/22228082/44003352-fab501b4-9e16-11e8-8f62-25ac3115b03e.PNG)

**Comment by Gabrielmines** [comment]
:( im sorry for swaering im just bummed out

**Comment by Gabrielmines** [comment]
okay ill try and restart my computer or reinstall it

**Comment by Gabrielmines** [comment]
its not working just saying fatal error

**Comment by Gabrielmines** [comment]
[citra_log.txt](https://github.com/valentinvanelslande/citra/files/2281069/citra_log.txt)

**Comment by Gabrielmines** [comment]
my version is 413

**Comment by Gabrielmines** [comment]
![citra valentin 413 _ tomodachi life 8_12_2018 12_05_50 pm](https://user-images.githubusercontent.com/37378147/44003641-3a1ffe20-9e2c-11e8-872f-aa6c711ee802.png)

**Comment by valentinvanelslande** [comment]
i think your rom is corrupt

**Comment by Gabrielmines** [comment]
just fixed it the rom was corrupt thanks for helping! :D
