### ISSUE TITLE
citra "CrashDumps"

### ISSUE THREAD

**Issue by rcyggdra** [valentinvanelslande/citra#417]
![snipaste_2018-08-21_18-24-12](https://user-images.githubusercontent.com/8652464/44396466-88ceb080-a56f-11e8-87ca-5173124c883c.png)
As the pic show,when the citra-valentin(mingw) run a game & closed,Windows bulid .dmp file on
Win10:%username%\AppData\Local\CrashDumps
citra-nightly,citra-valentin(msvc latest)&citra-valentin(mingw before 438) work fine.

**Comment by valentinvanelslande** [comment]
no log

**Comment by rcyggdra** [comment]
[citra_log.txt](https://github.com/valentinvanelslande/citra/files/2306966/citra_log.txt)

**Comment by valentinvanelslande** [comment]
citra crashes?

**Comment by rcyggdra** [comment]
citra no crash,but close it still run background a few.

**Comment by valentinvanelslande** [comment]
how are you closing citra? close the console, the window or with the task manager?
and you have a game running when you close citra?

**Comment by rcyggdra** [comment]
both, and this is console:
![snipaste_2018-08-21_23-46-53](https://user-images.githubusercontent.com/8652464/44412889-8e8ebb00-a59c-11e8-9967-a7800afda794.png)

**Comment by rcyggdra** [comment]
work fine on citra_487-mingw,no CrashDumps.
