### ISSUE TITLE
why remove shared font support?

### ISSUE THREAD

**Issue by rcyggdra** [valentinvanelslande/citra#423]
that's a bad idea,I recommend to keep it.
i'm chinese,bad english,play translation games.
some game need to set Japan/USA region with DLC.
but the font not complete(for chinese),so we using shared font make it OK & change font style.

![snipaste_2018-08-28_01-24-07](https://user-images.githubusercontent.com/8652464/44674936-9e594400-aa61-11e8-992e-5aa860072a27.png)
the pic show:
top:Japan region,the font not complete.
mid:China region,not support DLC in some game(e.g. metal max 4) and worst font style.
bottom:Japan region,using shared font.

**Comment by valentinvanelslande** [comment]
i only removed loading shared font from shared_font.bin. dump the shared fonts using the new method
