### ISSUE TITLE
Citra 490 44cd805. Empty "Region" column.

### ISSUE THREAD

**Issue by Darkness4** [valentinvanelslande/citra#424]
Hello,
I don't know if this bug is intended, but the "Region" column is empty in 44cd805.

Citra also crashes if the game region is invalid. 
I had to uninstall the game to launch Citra. 

[citra_log_490_empty_region.txt](https://github.com/valentinvanelslande/citra/files/2328141/citra_log_490_empty_region.txt)
[citra_log_489_normal_boot.txt](https://github.com/valentinvanelslande/citra/files/2328142/citra_log_489_normal_boot.txt)
[citra_log_490_crash.txt](https://github.com/valentinvanelslande/citra/files/2328145/citra_log_490_crash.txt)

Citra 489 d41f91c597ad92d24cb49d75b7c7ce2f859d4005 normal boot : 
![citra 489 normal boot](https://user-images.githubusercontent.com/18192844/44725254-2a588380-aad5-11e8-99b1-361248884307.png)
Citra 490 44cd805 crash (1s before the crash, citra is actually frozen) : 
![citra 490 crash](https://user-images.githubusercontent.com/18192844/44725255-2a588380-aad5-11e8-9152-d4b1aea8c598.png)
Citra 490 44cd805 empty region (after uninstalling the invalid game) : 
![citra 490 empty region](https://user-images.githubusercontent.com/18192844/44725256-2af11a00-aad5-11e8-988a-b29c0d987019.png)

EDIT : Alright, i found the fix, I rolled back the changes in src/citra_qt/game_list_p.h @@ -365,14 +378,12 @@ class GameListItemRegion : public GameListItem {.

Because, if isValidSMDH is true, it's missing "setText(GetRegionFromSMDH(smdh));" because it moved.
And if it isn't, i'm guessing that loading invalid smdh data crashes Citra.

**Comment by valentinvanelslande** [comment]
reproduced. will fix soon.
