### ISSUE TITLE
Citra Valentin #502 Pokemon X

### ISSUE THREAD

**Issue by DanielBueno26** [valentinvanelslande/citra#428]
Hi, Pokemon X is working in menu but I can't hear any sound, only when I change the language, besides when Professor stop talk and go to in-game, the game crash and I get a black screen. Any solution? 👍 
Ultra Moon is working perfectly and is newer than Pokemon X, so i'm hyper confused.
Regards.

**Comment by valentinvanelslande** [comment]
this issue has no solution
