### ISSUE TITLE
shared font file missing

### ISSUE THREAD

**Issue by rcyggdra** [valentinvanelslande/citra#431]
same "user" folder,but your build can't run.
[canacy_citra_log.txt](https://github.com/valentinvanelslande/citra/files/2341202/canacy_citra_log.txt)
[valentin_citra_log.txt](https://github.com/valentinvanelslande/citra/files/2341211/valentin_citra_log.txt)

**Comment by valentinvanelslande** [comment]
dump the system archives from your 3ds

**Comment by rcyggdra** [comment]
taht's your build can't load shared font file,can you see the canacy log?
i know system archives & i put it in.
canary:[   4.427543] Service.APT <Warning> core/hle/service/apt/apt.cpp:GetSharedFont:200: Loaded shared font by legacy method

yours:[3.695633] Service.APT <Error> core/hle/service/apt/apt.cpp:GetSharedFont:180: shared font file missing - go dump it from your 3ds

**Comment by rcyggdra** [comment]
#423  we need use shared font on  Japan region.
that‘s wahy  i ask you removed shared_font.bin support.

**Comment by rcyggdra** [comment]
you make citra better than official build,why do not make friendly for user?
