### ISSUE TITLE
Luigi's Mansion 2 crashes on boot

### ISSUE THREAD

**Issue by valentinvanelslande** [valentinvanelslande/citra#433]
`[1.590205] Debug <Critical> core/arm/dynarmic/arm_dynarmic.cpp:operator():164: Assertion Failed!
ExceptionRaised(exception = 1, pc = 005277DC, code = E320F000)
`

**Comment by EmulationChannel** [comment]
core/cpu/cpu.cpp:operator():100: Assertion Failed!
