### ISSUE TITLE
error multijugador

### ISSUE THREAD

**Issue by Maxdex6** [valentinvanelslande/citra#445]
no puedo jugar multijugador me sale este error cuando me intento conectar a una sala, 
![captura](https://user-images.githubusercontent.com/42588598/45337196-417b8480-b55d-11e8-8aa3-f115f4735d2b.PNG)
ayuda. podrian explicarme como hacerlo?

**Comment by valentinvanelslande** [comment]
pon en IP la IP privada y no la IP pública

**Comment by Maxdex6** [comment]
Muchas gracias lo probare!!
