### ISSUE TITLE
Animal Crossing New Leaf - Infinite loading error on release of 580

### ISSUE THREAD

**Issue by GimoXagros** [valentinvanelslande/citra#448]
![001](https://user-images.githubusercontent.com/30635204/45593055-27f09780-b9b8-11e8-89cb-f32453667404.JPG)
![002](https://user-images.githubusercontent.com/30635204/45593057-2921c480-b9b8-11e8-9e24-7161ae759684.JPG)

The game will not start on the first loading screen. Perhaps there is a problem with the internal options (user-nand-data). Nightly version worked fine.

CPU: Intel(R) Core(TM) i7 CPU 870 @2.93GHz 2.93GHz
RAM: 16GB DDR3
GPU: GTX 460

[citra_log.txt](https://github.com/valentinvanelslande/citra/files/2386313/citra_log.txt)

**Comment by valentinvanelslande** [comment]
how did you dump your game?
and screenshots of all the configuration tabs, control panel and cheats?

**Comment by GimoXagros** [comment]
![01](https://user-images.githubusercontent.com/30635204/45597574-4b8ffe00-ba09-11e8-9894-f5f80c65a265.JPG)
![02](https://user-images.githubusercontent.com/30635204/45597576-4d59c180-ba09-11e8-80c0-09ac45949d13.JPG)
![03](https://user-images.githubusercontent.com/30635204/45597577-4df25800-ba09-11e8-9ccf-06e7145828dd.JPG)
![04](https://user-images.githubusercontent.com/30635204/45597579-4fbc1b80-ba09-11e8-808a-8882aadb47b9.JPG)
![05](https://user-images.githubusercontent.com/30635204/45597580-5054b200-ba09-11e8-9bb4-1dca7bd64c21.JPG)
![06](https://user-images.githubusercontent.com/30635204/45597581-5185df00-ba09-11e8-820e-c0eaf0202665.JPG)

Yes. This file is dumped to 3DS.

**Comment by valentinvanelslande** [comment]
i removed system files from your comment.
disable enable priority boost

**Comment by GimoXagros** [comment]
Thank you. The issue has been resolved. I have confirmed that it works properly in the 584 version.

The enable priority boost option also works.
