### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by Maxdex6** [valentinvanelslande/citra#449]
Hola esto es una pregunta sobre el soprote de la carpeta user; como hacemos para usar las nuevas versones de citra y mantener nuestra partida? o eso ya no se puede hacer? saludos!

**Comment by valentinvanelslande** [comment]
mueve las carpetas de la carpeta user a %appdata%/Citra

**Comment by Maxdex6** [comment]
muchas gracias! sigue asi!
