### ISSUE TITLE
No Graphic Enhancement on the new Version Citra valentine 602

### ISSUE THREAD

**Issue by Sabriana** [valentinvanelslande/citra#450]
Are these normal ? Can you fix this or help me figure it out how to make it possible to upscale the graphic ?
--->
![no enhancement option for the graphic](https://user-images.githubusercontent.com/43429850/45795014-ae142300-bcc3-11e8-9b5c-9bcf95adbd12.png)
![no enhancement option for new citra valentine 602](https://user-images.githubusercontent.com/43429850/45795070-f2072800-bcc3-11e8-98bd-9efd7db7ee7f.png)

**Comment by valentinvanelslande** [comment]
wait for the next build
