### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Resit3** [valentinvanelslande/citra#454]
why do u removed support for CPUs without SSE4.1?? 
:/ i cant use your builds anymore ;_;

**Comment by valentinvanelslande** [comment]
because i wanted.

**Comment by Resit3** [comment]
Dont need to be rude, but i understand, those people from 3º world can not argue decently, they did not learn education too, probably a street dog in my country has more politeness.
So u can go You can go fuck yourself, you piece of shit.
